language: node_js
node_js:
  - "10"
  - "8"
  - "6"
  - "4"
  - "iojs"
before_install:
  - 'nvm install-latest-npm'
script:
  - 'if [ -n "${LINT-}" ]; then npm run lint ; fi'
  - 'if [ "${TEST-}" = true ]; then npm run tests-only ; fi'
env:
  global:
    - TEST=true
  matrix:
    - REACT=0.14
    - REACT=15
    - REACT=16
sudo: false
matrix:
  fast_finish: true
  include:
    - node_js: "lts/*"
      env: LINT=true TEST=false
  allow_failures:
    - node_js: "iojs"
